config/routes.rb
Rails.application.routes.draw do
  get "inquiry" => "inquiry#index"
  post "inquiry/confirm" => "inquiry#confirm"
  post "inquiry/thanks" => "inquiry#thanks"

  get "inquiry/index"
  get "inquiry/confirm"
  get "inquiry/thanks"
  root "home#index"

  get "sessions/new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "people/add"
  post "people/add", to: "people#create"
  get "people/index"
  get "people", to: "people#index"
  get "people/thanks"

  get "/photo_list/show"
  get "/photo_list", to: "photo_list#show"

  resources :photo_list do
    get :search, on: :collection
  end

  get "/photo_details/:id" => "photo_details#show"

  get "/locations", to: "locations#show"
  get "locations/thanks"
  post "/locations/create", to: "locations#create"

  get "home/index"
  get "home", to: "home#index"

  get "inquiry/question"
  get "inquiry", to: "inquiry#question"

  get "account/account_information"
  get "account", to: "account#account_information"

  get "login/login_form"
  get "login", to: "login#login_form"

  get "registration/registration_form"
  get "registration", to: "registration#registration_form"

  get "details/slide_details"
  get "details", to: "details#slide_details"

  get "about/about_write"
  get "about", to: "about#about_write"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => { :message => "名前を入力してください" }
  validates :email, :presence => { :message => "メールアドレスを入力してください" }
end

app/models/location.rb
class Location < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  validates :name, presence: true
  validates :prefecture, presence: true
  validates :municipalities, presence: true
  validates :address, presence: true
  validates :photo, presence: true
  validates :photo_description, presence: true

end

app/models/person.rb
class Person < ApplicationRecord
  include BCrypt
  has_secure_password

  validates :name, presence: true

  validates :age, presence: true
  validates :age, length: { maximum: 3 }
  validates :age, numericality: true

  validates :email, presence: { message: "を入力してください" }
  validates :email, uniqueness: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
end

app/models/spot.rb
class Spot < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :logged_in_people, only: [:edit, :update, :destroy]

  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/helo_helper.rb
module HeloHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/photo_list_helper.rb
module PhotoListHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(people)
    session[:people_id] = people.id
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_people
    if session[:people_id]
      @current_people ||= Person.find_by(id: session[:people_id])
    end
  end

  #受け取ったユーザーがログイン中のユーザーと一致すればtrueを返す
  def current_people?(people)
    people == current_people
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_people.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:people_id)
    @current_people = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/about_write.html.erb
<h1>このアプリについて</h1>
<h2>■概要</h2>
<p class = "explanation">インスタ映えするスポットを自由に投稿、閲覧できるWebアプリです。 画像を投稿フォームから投稿でき、投稿画像一覧から詳細画面に遷移します。</p>
<h2>■機能一覧</h2>

<div class="list">
<ul>
    <li>ログイン機能</li>
    <li>ユーザ登録機能</li>
    <li>画像投稿機能</li>
    <li>投稿画像一覧表示機能</li>
    <li>投稿画像詳細情報表示機能</li>
    <li>お問合せ機能</li>
</ul>
</div>
<h2>■使用技術</h2>
<ul>
    <li>ruby 2.6.6</li>
    <li>rails 5.2.4.4</li>
    <li>DB MySQL 8.0.23</li>
    <li>デプロイ先 AWS EC2</li>
    <li>スライドショー skipper</li>
    <li>画像加工 ImageMagick 7.0.11-Q16-HDRI, Rmagick 4.2.2</li>
    <li>画像アップロード CarrierWave 2.1.0</li>
    <li>単体、結合テスト RSpec 3.10</li>
</ul>

app/views/home/_logged_in.html.erb

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">


<div class="flex">

    <div class="to-photo_list-button-wrapper">
        <%= button_to photo_list_path, method: :get, class: "to-photo_list-button" do %>
            <i class="fa fa-caret-right"></i> 投稿画像一覧へ
        <% end %>
    </div>

    <div class="to-locations-button-wrapper">
        <%= button_to locations_path, method: :get, class: "to-locations-button" do %>
            <i class="fa fa-caret-right"></i> 新規投稿
        <% end %>
    </div>
</div>


<div class="button_wrapper">
    <%= link_to(logout_path, method: :delete) do %>
        <button class="logout-button" >ログアウト</button>
    <% end %>
</div>

app/views/home/_not_logged_in.html.erb



<div class="flex">

    <div class="to-photo_list-button-wrapper">
        <%= button_to photo_list_path, method: :get, class: "to-photo_list-button" do %>
            <i class="fa fa-caret-right"></i> 投稿画像一覧へ
        <% end %>
    </div>

    <div class="to-locations-button-wrapper">
        <%= button_to locations_path, method: :get, class: "to-locations-button" do %>
            <i class="fa fa-caret-right"></i> 新規投稿
        <% end %>
    </div>
</div>


app/views/home/index.html.erb


<% if logged_in? %>
  <%= render "home/logged_in" %>
<% else %>
  <%= render "home/not_logged_in" %>
<% end %>