config/routes.rb
Rails.application.routes.draw do
  get "inquiry" => "inquiry#index"
  post "inquiry/confirm" => "inquiry#confirm"
  post "inquiry/thanks" => "inquiry#thanks"

  get "inquiry/index"
  get "inquiry/confirm"
  get "inquiry/thanks"
  root "home#index"

  get "sessions/new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "people/add"
  post "people/add", to: "people#create"
  get "people/index"
  get "people", to: "people#index"
  get "people/thanks"

  get "/photo_list/show"
  get "/photo_list", to: "photo_list#show"

  resources :photo_list do
    get :search, on: :collection
  end

  get "/photo_details/:id" => "photo_details#show"

  get "/locations", to: "locations#show"
  get "locations/thanks"
  post "/locations/create", to: "locations#create"

  get "home/index"
  get "home", to: "home#index"

  get "inquiry/question"
  get "inquiry", to: "inquiry#question"

  get "account/account_information"
  get "account", to: "account#account_information"

  get "login/login_form"
  get "login", to: "login#login_form"

  get "registration/registration_form"
  get "registration", to: "registration#registration_form"

  get "details/slide_details"
  get "details", to: "details#slide_details"

  get "about/about_write"
  get "about", to: "about#about_write"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => { :message => "名前を入力してください" }
  validates :email, :presence => { :message => "メールアドレスを入力してください" }
end

app/models/location.rb
class Location < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  validates :name, presence: true
  validates :prefecture, presence: true
  validates :municipalities, presence: true
  validates :address, presence: true
  validates :photo, presence: true
  validates :photo_description, presence: true

end

app/models/person.rb
class Person < ApplicationRecord
  include BCrypt
  has_secure_password

  validates :name, presence: true

  validates :age, presence: true
  validates :age, length: { maximum: 3 }
  validates :age, numericality: true

  validates :email, presence: { message: "を入力してください" }
  validates :email, uniqueness: true
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
end

app/models/spot.rb
class Spot < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :logged_in_people, only: [:edit, :update, :destroy]

  def index
  end
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => "index"
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => "confirm"
    else
      # NG。入力画面を再表示
      render :action => "index"
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => "thanks"
  end

  private

  def inquiry_params
    params.require(:inquiry).permit(:name, :email, :message)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/helo_helper.rb
module HeloHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/photo_list_helper.rb
module PhotoListHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # 渡されたユーザーでログインする
  def log_in(people)
    session[:people_id] = people.id
  end

  # 現在ログイン中のユーザーを返す (いる場合)
  def current_people
    if session[:people_id]
      @current_people ||= Person.find_by(id: session[:people_id])
    end
  end

  #受け取ったユーザーがログイン中のユーザーと一致すればtrueを返す
  def current_people?(people)
    people == current_people
  end

  # ユーザーがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_people.nil?
  end

  # 現在のユーザーをログアウトする
  def log_out
    session.delete(:people_id)
    @current_people = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inquiry/confirm.html.erb
<div class="newWrap">
  <div class="newTitle">
    <h1>下記内容で送信します。よろしいですか？</h1>
  </div>
  <div class="confirm-contents">
    <%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
    <div class="confirm-items">
      <div class="col-sm-4">名前</div>
      <div class="col-sm-8"><%= f.hidden_field :name %><%= @inquiry.name %></div>
      <div class="col-sm-4">メールアドレス</div>
      <div class="col-sm-8"><%= f.hidden_field :email %><%= @inquiry.email %></div>
      <div class="col-sm-4">お問い合わせ内容</div>
      <div class="col-sm-8"><%= f.hidden_field :message %><%= simple_format(@inquiry.message) %></div>
    </div>
    <div class="button_wrapper">
      <%= f.submit "送信する", class: "btn btn-block btn-success" %>
    </div>
    <% end %>
  </div>
</div>

app/views/inquiry/index.html.erb
<% @page_title = "お問い合わせ" %>
<div class="newWrap">
  <div class="newTitle">
    <h1>お問い合わせ</h1>
  </div>
  <div class="newContent">
    <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
      <% if @inquiry.errors.any? %>
        <div class="alert-danger" role="alert">
          <ul>
            <% @inquiry.errors.each do |attr, msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="inquiry-form">
        <div class="form-text">名前<span class="text-danger">（必須）</span></div>
        <%= f.text_field :name, class: "inquiry-input-information" %>
        <div class="form-text">メールアドレス<span class="text-danger">（必須）</span></div>
        <%= f.text_field :email, class: "inquiry-input-information" %>
        <div class="form-text">お問い合わせ内容</div>
        <%= f.text_area :message, size: "50x10", class: "inquiry-contents" %>
      </div>
      <div class="button_wrapper">
        <%= f.submit "確認", class: "btn btn-block btn-success" %>
      </div>

    <% end %>
  </div>
</div>

app/views/inquiry/thanks.html.erb
<div class="newWrap">
  <div class="newTitle">
    <h1>お問い合わせ：送信しました</h1>
  </div>
  <div class="thanks-message">
    <p>お問い合わせありがとうございます。</p>
    <p>後日管理人より返信メールが届きます。</p>
  </div>
</div>